# conda update --all
# conda env create -f environment_bonebox.yml
# conda env remove -n main

name: bonebox
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - numba
  - mkl
  - matplotlib
  - scikit-image
  - scikit-learn
  #- spyder
  - ipython
  - glob2
  # - projectchrono::pychrono
  - pip
  - pynrrd # image/data file formats
  - pydicom
  - h5py
  - nibabel
  # - meshio # mesh formats
  # - trimesh
  - tetgen
  - vtk
  - pyvista
  - pyvistaqt
  # - pyradiomics # -c radiomics
  - umap-learn # ML
  - edt # Euclidean Distance Transform and Skeletal Analysis (3D-capable)
  - skan
  - cvxopt # convex optimization
  - pytorch # cudatoolkit=11.3 -c pytorch
  - torchvision # cudatoolkit=11.3 -c pytorch
  - torchaudio # cudatoolkit=11.3 -c pytorch
  # Add by Ran:
  - monai # PyTorch-based framework for deep learning in healthcare imaging (can be 3D image)
  - skorch # A scikit-learn compatible neural network library that wraps PyTorch.
  # - python-utils # Remove this package!!!
  - tensorboard # may not need